[package]
name = "rustwav"
version = "0.0.22"
edition = "2024"
authors = ["0xAA55 <838816058@qq.com>"]
readme = "Readme.md"
license-file = "LICENSE"
description = "WAV format audio file parser and creator, with resampler, can change the sample rate of the audio file, and a lot of sub-format support e.g. ADPCM, aLaw, MuLaw, mp3, opus, flac, etc."
repository = "https://github.com/0xAA55-rs/rustwav"
keywords = ["audio", "WAV"]

[dependencies]
encoding = { version = "0.2.33", optional = true }
flac-rs = { version = "0.0.6", optional = true }
id3 = { version = "1.16.2", optional = true }
mp3lame-encoder = { version = "0.2.1", optional = true }
opus = { version = "0.3.0", optional = true}
rmp3 = { version = "0.3.1", optional = true, features = ["mp1-mp2", "std"] }
vorbis_rs = { version = "0.5.5", optional = true}
resampler-rs = "0.0.1"
sampletypes = "0.1.2"
tempfile = "3.18.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.1", features = ["Win32_Foundation", "Win32_Globalization"]}

[features]
default = ["id3", "text_encoding", "mp3dec", "mp3enc", "opus", "flac", "vorbis"]
text_encoding = ["dep:encoding"]
id3 = ["dep:id3"]
mp3dec = ["dep:rmp3"]
mp3enc = ["dep:mp3lame-encoder"]
opus = ["dep:opus"]
flac = ["dep:flac-rs"]
vorbis = ["dep:vorbis_rs"]

[profile.release]
lto = "fat"

[lib]
name = "rustwav"
path = "src/lib.rs"
