[package]
name = "rustwav"
version = "0.1.0"
edition = "2021"
authors = ["0xAA55 <838816058@qq.com>"]

[dependencies]
encoding = "0.2.33"
id3 = "1.16.2"
tempfile = "3.18.0"

windows = { version = "0.61.1", features = ["Win32_Foundation", "Win32_Globalization"]}

[features]
default = ["id3"]

[lib]
name = "rustwav_lib"
path = "src/lib.rs"

[[bin]]
name = "rustwav_bin"
path = "src/test.rs"
