[package]
name = "rustwav"
version = "0.0.12"
edition = "2021"
authors = ["0xAA55 <838816058@qq.com>"]
description = "WAV format audio file parser and creator, with resampler, can change the sample rate of the audio file, and a lot of sub-format support e.g. ADPCM, aLaw, MuLaw, mp3, opus, flac, etc."

[dependencies]
encoding = { version = "0.2.33", optional = true }
id3 = { version = "1.16.2", optional = true }
libflac-sys = { version = "0.3.2", optional = true, default-features = false, features = ["build-flac"] }
mp3lame-encoder = { version = "0.2.1", optional = true }
opus = { version = "0.3.0", optional = true}
rmp3 = { version = "0.3.1", optional = true, features = ["mp1-mp2", "std"] }
rustfft = "6.2.0"
tempfile = "3.18.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.1", features = ["Win32_Foundation", "Win32_Globalization"]}

[features]
default = ["id3", "text_encoding", "mp3dec", "mp3enc", "opus", "flac"]
text_encoding = ["dep:encoding"]
id3 = ["dep:id3"]
mp3dec = ["dep:rmp3"]
mp3enc = ["dep:mp3lame-encoder"]
opus = ["dep:opus"]
flac = ["dep:libflac-sys"]

[profile.release]
lto = "fat"

[lib]
name = "rustwav_lib"
path = "src/lib.rs"

[[bin]]
name = "rustwav_bin"
path = "src/test.rs"
