[package]
name = "xlaw"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
description = "PCM-aLaw and PCM-MuLaw codecs."
keywords = ["PCM", "alaw", "ulaw", "mulaw", "audio"]

[dependencies]

[lib]
name = "xlaw"
path = "src/xlaw.rs"
