[package]
name = "revorbis-rs"
version = "0.0.2"
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
description = "A try to rewrite libvorbis in Rust."
keywords = ["vorbis", "audio"]

[dependencies]
tinyogg.workspace = true
copiablebuf.workspace = true
shared_io_utils.workspace = true

[profile.release]
lto = "fat"

[lib]
name = "revorbis"
path = "src/vorbis.rs"
