[package]
name = "downmixer"
version = "0.0.2"
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
description = "A downmixer that can do 2, Dolby 2.1, 3.1, 4.1, 5.1, 6.1, 7.1 channels audio downmix to 2 or 1 channels in Rust."
keywords = ["downmixer", "audio"]

[dependencies]
copiablebuf.workspace = true
sampletypes.workspace = true

[lib]
name = "downmixer"
path = "src/downmixer.rs"
