[package]
name = "bitwise"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]

[lib]
name = "bitwise"
path = "src/bitwise.rs"
