[package]
name = "io_utils"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
savagestr.workspace = true

[lib]
name = "io_utils"
path = "src/io_utils.rs"
