[package]
name = "rustwav-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
description = "The core implementation of WAV format audio file parser and creator, with resampler and downmixer, can change the sample rate of the audio file, and a lot of sub-format support e.g. ADPCM, aLaw, MuLaw, mp3, opus, flac, ogg vorbis, etc, can't use directly, please use `rustwav`."
keywords = ["audio", "WAV", "codec", "RIFF"]

[dependencies]
xlaw.workspace = true
tinyogg.workspace = true
downmixer.workspace = true
savagestr.workspace = true
revorbis-rs.workspace = true
copiablebuf.workspace = true
fileparthasher.workspace = true
shared_io_utils.workspace = true
audiochannelutils.workspace = true

tempfile.workspace = true
sampletypes.workspace = true
resampler-rs.workspace = true

flac-rs = { version = "0.0.6", optional = true }
id3 = { version = "1.16.2", optional = true }
mp3lame-encoder = { version = "0.2.1", optional = true }
opus = { version = "0.3.0", optional = true}
rmp3 = { version = "0.3.1", optional = true, features = ["mp1-mp2", "std"] }
vorbis_rs = { version = "0.5.5", optional = true}

[features]
default = ["id3", "mp3dec", "mp3enc", "opus", "flac", "vorbis", "oggvorbis"]
id3 = ["dep:id3"]
mp3dec = ["dep:rmp3"]
mp3enc = ["dep:mp3lame-encoder"]
opus = ["dep:opus"]
flac = ["dep:flac-rs"]
vorbis = ["dep:vorbis_rs"]
oggvorbis = ["dep:vorbis_rs"]

[lib]
name = "rustwav_core"
path = "src/lib.rs"
