[package]
name = "copiablebuf"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
description = "Copiable buffer, a tinier `Vec`, uses a fixed-size array to store a variable number of items."
keywords = ["container", "buffer", "array"]

[dependencies]

[lib]
name = "copiablebuf"
path = "src/copiablebuf.rs"
